version: '3.9'

services:
    postgres:
        image: postgres
        container_name: ${PG_CONTAINER_NAME}
        restart: unless-stopped
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}
        volumes:
          - ${PGDATA}:/var/lib/postgresql/data
        ports:
          - ${PGPORT}:5432
        networks:
          - app_network

    go-web-api:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: co2monitor.api
        environment:
          DATABASE_URL: ${DATABASE_URL}
        networks:
          - app_network
        restart: unless-stopped
        ports:
          - 8080:8080
        depends_on:
          - postgres
        volumes:
          - api_logs:/app/logs

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  api_logs: