version: '3.9'

services:
    go-web-api:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: co2monitor.api
        environment:
          DATABASE_URL: ${DATABASE_URL}
        networks:
          - co2_monitor_network
          - traefik_web
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.go-web.rule=Host(`co2.leyrer.io`)"
        restart: unless-stopped
        volumes:
          - ./logs/:/app/logs/


networks:
  co2_monitor_network:
    driver: bridge
  traefik_web:
    external: true

volumes:
  api_logs: